### ISSUE TITLE
tabStrip

### ISSUE THREAD

**Issue by nickradford** [philcockfield/open.core#22]
The tabStrip should have a roundedCorners property.

The resulting css should work such that: 

``` css
    .core_tab.core_enabled.core_first {
        border-top-left-radius: inherit;
    }
```

This will make the first tab inherit the top-left radius of it's parent element.
